services:
  - type: web
    name: go-project-278-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
    healthCheckPath: /ping
    healthCheckTimeout: 30
    autoDeploy: true